# Generated by Django 5.0.4 on 2026-01-03 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Billboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='billboards/')),
                ('sqft', models.IntegerField(help_text='Total Square Feet')),
                ('size', models.CharField(help_text='Dimensions (e.g., 20x10)', max_length=50)),
                ('location', models.CharField(max_length=200)),
                ('map_url', models.URLField(blank=True, help_text='Google Maps Embed Link or URL', max_length=500)),
                ('is_available', models.BooleanField(default=True)),
                ('price_per_month', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_phone', models.CharField(max_length=20)),
                ('start_date', models.DateField()),
                ('duration_months', models.IntegerField(default=1)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('billboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billboards.billboard')),
            ],
        ),
    ]
