# Generated by Django 5.2.9 on 2026-01-03 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billboards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='billboard',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed description of the billboard location and advantages'),
        ),
    ]
